Repository OCA/agreement, pull requests merged in 2024-12, with the labels that each got.

#50 [18.0][MIG] agreement: Migration to 18.0
  agreement/README.rst
  agreement/__init__.py
  agreement/__manifest__.py
  agreement/demo/demo.xml
  agreement/i18n/agreement.pot
  agreement/i18n/ca.po
  agreement/i18n/de.po
  agreement/i18n/es.po
  agreement/i18n/es_AR.po
  agreement/i18n/fr.po
  agreement/i18n/fr_FR.po
  agreement/i18n/hr.po
  agreement/i18n/it.po
  agreement/i18n/nl.po
  agreement/i18n/pt.po
  agreement/i18n/pt_BR.po
  agreement/i18n/pt_PT.po
  agreement/i18n/zh_CN.po
  agreement/models/__init__.py
  agreement/models/agreement.py
  agreement/models/agreement_type.py
  agreement/pyproject.toml
  agreement/readme/CONTRIBUTORS.md
  agreement/readme/CREDITS.md
  agreement/readme/DESCRIPTION.md
  agreement/security/agreement_security.xml
  agreement/security/ir.model.access.csv
  agreement/static/description/icon.png
  agreement/static/description/index.html
  agreement/tests/__init__.py
  agreement/tests/test_agreement.py
  agreement/views/agreement.xml
  agreement/views/agreement_menu.xml
  agreement/views/agreement_type.xml
Labels: needs review, migration, ready to merge, approved, bot is merging ⏳

#37 [16.0] [MIG] agreement_serviceprofile: Migration to 16.0
  agreement_serviceprofile/README.rst
  agreement_serviceprofile/__init__.py
  agreement_serviceprofile/__manifest__.py
  agreement_serviceprofile/data/serviceprofile_stage.xml
  agreement_serviceprofile/i18n/agreement_serviceprofile.pot
  agreement_serviceprofile/i18n/de.po
  agreement_serviceprofile/i18n/en_US.po
  agreement_serviceprofile/i18n/es.po
  agreement_serviceprofile/i18n/es_AR.po
  agreement_serviceprofile/i18n/fr.po
  agreement_serviceprofile/i18n/pt.po
  agreement_serviceprofile/i18n/pt_BR.po
  agreement_serviceprofile/i18n/zh_CN.po
  agreement_serviceprofile/migrations/16.0.1.0.0/post-migration.py
  agreement_serviceprofile/models/__init__.py
  agreement_serviceprofile/models/agreement.py
  agreement_serviceprofile/models/agreement_serviceprofile.py
  agreement_serviceprofile/models/agreement_stage.py
  agreement_serviceprofile/models/product.py
  agreement_serviceprofile/readme/CONTRIBUTORS.rst
  agreement_serviceprofile/readme/DESCRIPTION.rst
  agreement_serviceprofile/security/ir.model.access.csv
  agreement_serviceprofile/static/description/icon.png
  agreement_serviceprofile/static/description/index.html
  agreement_serviceprofile/tests/__init__.py
  agreement_serviceprofile/tests/test_agreement_serviceprofile.py
  agreement_serviceprofile/tests/test_product.py
  agreement_serviceprofile/views/agreement.xml
  agreement_serviceprofile/views/agreement_serviceprofile.xml
  agreement_serviceprofile/views/product.xml
  setup/agreement_serviceprofile/odoo/addons/agreement_serviceprofile
  setup/agreement_serviceprofile/setup.py
Labels: migration, bot is merging ⏳

#38 [16.0] [MIG] agreement_maintenance: Migration to 16.0
  agreement_maintenance/README.rst
  agreement_maintenance/__init__.py
  agreement_maintenance/__manifest__.py
  agreement_maintenance/i18n/agreement_maintenance.pot
  agreement_maintenance/i18n/de.po
  agreement_maintenance/i18n/es.po
  agreement_maintenance/i18n/es_AR.po
  agreement_maintenance/i18n/pt.po
  agreement_maintenance/i18n/pt_BR.po
  agreement_maintenance/i18n/zh_CN.po
  agreement_maintenance/models/__init__.py
  agreement_maintenance/models/agreement.py
  agreement_maintenance/models/agreement_serviceprofile.py
  agreement_maintenance/models/maintenance_equipment.py
  agreement_maintenance/models/maintenance_request.py
  agreement_maintenance/readme/CONFIGURE.rst
  agreement_maintenance/readme/CONTRIBUTORS.rst
  agreement_maintenance/readme/CREDITS.rst
  agreement_maintenance/readme/DESCRIPTION.rst
  agreement_maintenance/readme/USAGE.rst
  agreement_maintenance/static/description/icon.png
  agreement_maintenance/static/description/index.html
  agreement_maintenance/tests/__init__.py
  agreement_maintenance/tests/test_agreement_maintenance.py
  agreement_maintenance/views/agreement_serviceprofile_view.xml
  agreement_maintenance/views/agreement_view.xml
  agreement_maintenance/views/maintenance_equipment_view.xml
  agreement_maintenance/views/maintenance_request_view.xml
  setup/agreement_maintenance/odoo/addons/agreement_maintenance
  setup/agreement_maintenance/setup.py
Labels: ready to merge, approved, bot is merging ⏳
