Repository OCA/agreement, pull requests merged in 2025-09, with the labels that each got.

#84 [18.0] [REF] agreement_rebate: invoice creation revamp (and so FIX the red build on 18.0)
  agreement_rebate/models/__init__.py
  agreement_rebate/models/account_move.py
  agreement_rebate/models/account_move_line.py
  agreement_rebate/models/agreement_rebate_settlement.py
  agreement_rebate/tests/test_agreement_rebate.py
  agreement_rebate/wizards/invoice_create.py
Labels: ready to merge, approved, bot is merging ⏳

#79 [18.0][IMP] agreement_rebate: Improve test to create TestAgreementRebateBase
  agreement_rebate/data/agreement_rebate_data.xml
  agreement_rebate/tests/test_agreement_rebate.py
Labels: approved, bot is merging ⏳

#85 [16.0][FIX] agreement_legal_ fix security issue
  agreement_legal/models/res_partner.py
Labels: ready to merge, approved
